repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.27.0
    hooks:
      - id: golangci-lint
        args: [--enable, goimports]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: node_modules/.bin/prettier --write
        language: node
        files: \.(js|jsx)$
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: node_modules/.bin/eslint --ext .js,.jsx --max-warnings=0
        language: node
        files: \.(js|jsx)$
